spring:
  datasource:
    url: jdbc:h2:mem:jpa-practice
    username: sa
    password:
  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
