spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       show_sql: true <= 콘솔에 하이버네이트 실행 sql을 남긴다.
        format_sql: true
        use_sql_comments: true # <= JPQL 확인
logging.level:
  org.hibernate.SQL: debug # <= 로그에 하이버네이트 실행 sql을 남긴다.